"""flowlab: a deliberately small interpreter for the Power Automate / Logic Apps workflow-definition language.

It exists so the flow definitions generated by pou_flows can be EXECUTED in tests against the SharePoint model
(pou_tools.fakesp) with concurrency and fault injection. It is NOT the real Power Automate engine: semantics were
implemented from the published expression reference and may differ in corner cases. Anything this interpreter
accepts must still be validated in a tenant (see docs/11_Validation_Status.md).
"""
